extends: default

ignore: |
  node_modules/

rules:
  line-length:
    max: 130
  document-start: disable
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
